### ISSUE TITLE
Numerical Instability due to Logarithm

### ISSUE THREAD

**Issue by miraodasilva** [skaws2003/pytorch-mfcc#2]
I have experienced some numerical instability while using your MFCC. I believe it comes from the following two lines:
https://github.com/skaws2003/pytorch-mfcc/blob/303f50ebefa2d49136ebd5fd297a71de6bd5d705/pytorch_mfcc/pytorch_mfcc.py#L111

https://github.com/skaws2003/pytorch-mfcc/blob/303f50ebefa2d49136ebd5fd297a71de6bd5d705/pytorch_mfcc/pytorch_mfcc.py#L115

I believe adding a "+1e-6" or some similarly small float to both of these logs fixes this numerical instability. Thanks.

**Comment by miraodasilva** [comment]
Hi,

Actually, there were many other sources of numerical instability in your code. I have fixed them and the code is now working well for me. Please let me know if you want me to add my version as a branch of this repo.

Thanks.

**Comment by skaws2003** [comment]
Sorry for late response.

Oh, that's embressing. As always, any contribution is welcomed and I would be very thankful if you make PR to this repo. Thank you for pointing it out.

**Comment by miraodasilva** [comment]
Ok sorry I am bit busy with atm and I would want to clean up the code before I do a Pull Request. I will get back to you on this when I have the code ready for the Pull Request. Also, thanks for making this rep public and for your response.

**Comment by skaws2003** [comment]
Thank your for your contribution! I will be waiting for it.
